# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "379db999296fcd515d9c4d2613882c5a"
name = "returnsx"
handle = "returnsx"
application_url = "https://fiji-van-personnel-goto.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Mandatory compliance webhooks (required for App Store)
  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

  # ReturnsX webhooks for risk management
  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/created"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/created"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_customers,write_customers,read_fulfillments,read_refunds,write_script_tags,read_script_tags"

[auth]
redirect_urls = ["https://fiji-van-personnel-goto.trycloudflare.com/auth/callback", "https://fiji-van-personnel-goto.trycloudflare.com/auth/shopify/callback", "https://fiji-van-personnel-goto.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
