# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "379db999296fcd515d9c4d2613882c5a"
name = "returnsx"
handle = "returnsx"
application_url = "https://returnsx.pk"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Note: GDPR compliance webhooks (customers/data_request, customers/redact, shop/redact)
  # must be configured manually in the Shopify Partner Dashboard, not here.
  # See DEPLOYMENT_GUIDE.md for setup instructions.

  # ReturnsX webhooks for risk management
  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/created"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/webhooks/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/created"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Note: read_orders scope includes access to refund data - no separate read_refunds scope exists
scopes = "read_orders,write_orders,read_customers,write_customers,read_fulfillments,write_script_tags,read_script_tags"

[auth]
redirect_urls = ["https://returnsx.pk/auth/callback", "https://returnsx.pk/auth/shopify/callback", "https://returnsx.pk/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
