api_version = "2025-07"

[[extensions]]
uid = "c222e166-eee5-cfc5-a2b1-e0428e909500d87849fb"
type = "ui_extension"
name = "Order Status Risk Score"
handle = "order-status-risk-score"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.thank-you.block.render"
export = "thankYouRender"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "api_endpoint"
type = "single_line_text_field"
name = "API Endpoint"
description = "ReturnsX backend API endpoint for risk data"

[[extensions.settings.fields]]
key = "enable_debug"
type = "boolean"
name = "Enable Debug Mode"
description = "Show debug information in console"

[[extensions.settings.fields]]
key = "show_detailed_tips"
type = "boolean"
name = "Show Detailed Tips"
description = "Display improvement tips for customers"